In [75]:
import os
import torch

In [26]:
basedir = os.path.abspath('')[:-8]

In [27]:
with open(os.path.join(basedir, 'datasets\\names.txt'), 'r', encoding='utf-8') as file:
    lines = file.read().splitlines()
    
        

Length of dataset

In [28]:
len(lines)

32033

In [39]:
print(min([len(x) for x in lines]), max([len(x) for x in lines]))

2 15


In [100]:
from collections import defaultdict

bigram_dict = defaultdict(int)

for name in lines:
    name = ['<S>'] + list(name) + ['<E>']
    for x, y in zip(name, name[1:]):
        bigram = (x, y)
        bigram_dict[bigram] += 1

bigram_dict

defaultdict(int,
            {('<S>', 'e'): 1531,
             ('e', 'm'): 769,
             ('m', 'm'): 168,
             ('m', 'a'): 2590,
             ('a', '<E>'): 6640,
             ('<S>', 'o'): 394,
             ('o', 'l'): 619,
             ('l', 'i'): 2480,
             ('i', 'v'): 269,
             ('v', 'i'): 911,
             ('i', 'a'): 2445,
             ('<S>', 'a'): 4410,
             ('a', 'v'): 834,
             ('v', 'a'): 642,
             ('<S>', 'i'): 591,
             ('i', 's'): 1316,
             ('s', 'a'): 1201,
             ('a', 'b'): 541,
             ('b', 'e'): 655,
             ('e', 'l'): 3248,
             ('l', 'l'): 1345,
             ('l', 'a'): 2623,
             ('<S>', 's'): 2055,
             ('s', 'o'): 531,
             ('o', 'p'): 95,
             ('p', 'h'): 204,
             ('h', 'i'): 729,
             ('<S>', 'c'): 1542,
             ('c', 'h'): 664,
             ('h', 'a'): 2244,
             ('a', 'r'): 3264,
             ('r', 'l'): 

In [166]:
sorted_bigram = sorted(bigram_dict.items(), key=lambda x: x[1], reverse=True)
sorted_bigram

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [181]:
N = torch.zeros((27, 27), dtype=torch.int32)

In [191]:
chars = sorted(list(set(''.join(lines))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [192]:
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [193]:
for name in lines:
    name = ['.'] + list(name) + ['.']
    for x, y in zip(name, name[1:]):
        ix = stoi[x]
        iy = stoi[y]
        N[ix, iy] += 1

In [185]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [186]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'j'

Simple example how multinominal works

Multinominal uses probabilities to create array of given size ( num samples = 30)

In [187]:
p = torch.rand(3, generator=g)
p = p / p.sum()
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=30, replacement=True, generator=g)

print(p)
print(ix)

tensor([0.3344, 0.0995, 0.5661])
tensor([2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 1,
        2, 2, 0, 1, 2, 0])


In [236]:
P = (N+1).float()
P.sum(1, keepdim=True).shape

torch.Size([27, 1])

In [237]:
P = P / P.sum(1, keepdim=True)

In [238]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
    ix = 0
    name = ''
    while True:
        p = P[ix]# row 0 has starting characters
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        name += itos[ix]
        if ix == 0:
            print(name)
            name = ''
            break

junide.
janasah.
p.
cony.
a.


In [ ]:
# GOAL: maximize likelihood of the data w.r.t. model parameters (statistical modeling)
# equivalent to maximizing the log likelihood (because log is monotonic)
# equivalent to minimizing the negative log likelihood
# equivalent to minimizing the average negative log likelihood

# log(a*b*c) = log(a) + log(b) + log(c)

In [240]:
log_likelihood = 0.0
n = 0

for w in lines:
# for w in ["adamq"]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1, ix2]
    logprob = torch.log(prob)
    log_likelihood += logprob
    n += 1
    # print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

log_likelihood=tensor(-559938.8125)
nll=tensor(559938.8125)
2.4543004035949707


In [274]:
xs, ys = [], []
for name in lines[:1]:
    name = ['.'] + list(name) + ['.']
    for x, y in zip(name, name[1:]):
        ix = stoi[x]
        iy = stoi[y]
        xs.append(ix)
        ys.append(iy)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [276]:
import torch.nn.functional as F

xenc = F.one_hot(xs, num_classes=27).type(torch.float)
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Neuron prototype

In [277]:
W = torch.randn((27, 27))
logits = xenc @ W
counts = (xenc @ W).exp()#sigmoid activation
probs = counts / counts.sum(1, keepdim=True) # sigmoid activation
probs

tensor([[0.0155, 0.0888, 0.0316, 0.1077, 0.0076, 0.0083, 0.1459, 0.0141, 0.0252,
         0.0089, 0.0701, 0.0364, 0.0127, 0.0177, 0.0035, 0.1284, 0.0036, 0.0139,
         0.0409, 0.0176, 0.0304, 0.0045, 0.0439, 0.0324, 0.0063, 0.0302, 0.0539],
        [0.1060, 0.0124, 0.0030, 0.1851, 0.0209, 0.0078, 0.0175, 0.0011, 0.0103,
         0.0026, 0.0361, 0.0107, 0.0613, 0.0071, 0.0361, 0.0088, 0.0674, 0.0276,
         0.0148, 0.0086, 0.0352, 0.0356, 0.0446, 0.0634, 0.1592, 0.0118, 0.0050],
        [0.0219, 0.0086, 0.0741, 0.1109, 0.1246, 0.0252, 0.0096, 0.0053, 0.1165,
         0.0148, 0.0545, 0.0097, 0.0490, 0.0293, 0.0787, 0.0105, 0.0085, 0.0059,
         0.0790, 0.0141, 0.0230, 0.0232, 0.0278, 0.0046, 0.0308, 0.0340, 0.0057],
        [0.0219, 0.0086, 0.0741, 0.1109, 0.1246, 0.0252, 0.0096, 0.0053, 0.1165,
         0.0148, 0.0545, 0.0097, 0.0490, 0.0293, 0.0787, 0.0105, 0.0085, 0.0059,
         0.0790, 0.0141, 0.0230, 0.0232, 0.0278, 0.0046, 0.0308, 0.0340, 0.0057],
        [0.5077, 0.0113,

In [278]:
probs[0]

tensor([0.0155, 0.0888, 0.0316, 0.1077, 0.0076, 0.0083, 0.1459, 0.0141, 0.0252,
        0.0089, 0.0701, 0.0364, 0.0127, 0.0177, 0.0035, 0.1284, 0.0036, 0.0139,
        0.0409, 0.0176, 0.0304, 0.0045, 0.0439, 0.0324, 0.0063, 0.0302, 0.0539])

In [279]:
probs[0].shape

torch.Size([27])

In [280]:
probs[0].sum()

tensor(1.)

In [285]:
# randomly initialize 27 neurons' weights. each neuron receives 27 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

In [294]:
# forward pass
xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
loss = -probs[torch.arange(5), ys].log().mean()

In [295]:
print(loss.item())

3.7291626930236816


In [292]:
# backward pass
W.grad = None # set gradiant to zero
loss.backward()

In [293]:
W.data += -0.1 * W.grad

From these calculations above lets build simple one layer neural net

In [297]:
# create the dataset
xs, ys = [], []
for w in lines:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

number of examples:  228146


In [299]:
# gradient descent
for k in range(1000):
  
  # forward pass
  xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts, equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean()
  print(loss.item())
  
  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()
  
  # update
  W.data += -50 * W.grad

3.7686190605163574
3.3788065910339355
3.16109037399292
3.0271859169006348
2.9344842433929443
2.867231607437134
2.8166542053222656
2.777146339416504
2.7452542781829834
2.7188303470611572
2.696505546569824
2.6773719787597656
2.6608052253723145
2.6463515758514404
2.633664846420288
2.622471570968628
2.6125476360321045
2.6037068367004395
2.595794916152954
2.5886809825897217
2.5822560787200928
2.5764293670654297
2.5711236000061035
2.5662729740142822
2.5618228912353516
2.5577263832092285
2.5539441108703613
2.550442695617676
2.5471925735473633
2.5441696643829346
2.5413522720336914
2.538722038269043
2.536262035369873
2.5339581966400146
2.531797409057617
2.529768228530884
2.527859926223755
2.5260636806488037
2.5243701934814453
2.522773265838623
2.52126407623291
2.519836902618408
2.5184857845306396
2.5172054767608643
2.515990734100342
2.5148372650146484
2.5137407779693604
2.512697696685791
2.511704921722412
2.5107581615448
2.509854555130005
2.5089924335479736
2.5081682205200195
2.507380485534668


In [301]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
  
  out = []
  ix = 0
  while True:
    
    # ----------
    # BEFORE:
    #p = P[ix]
    # ----------
    # NOW:
    xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    p = counts / counts.sum(1, keepdims=True) # probabilities for next character
    # ----------
    
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

junide.
janasah.
p.
cfay.
a.
nn.
kohin.
tolian.
juwe.
ksahnaauranilevias.
